<a href="https://colab.research.google.com/github/Shohjahon02/first_my_git/blob/main/JSON.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
!git clone https://github.com/anvarnarz/praktikum_datasets.git

Cloning into 'praktikum_datasets'...
remote: Enumerating objects: 145, done.
remote: Counting objects: 100% (52/52), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 145 (delta 46), reused 43 (delta 43), pack-reused 93
Receiving objects: 100% (145/145), 9.72 MiB | 11.85 MiB/s, done.
Resolving deltas: 100% (53/53), done.

In [3]:
import json

x = 10
x_json = json.dumps(x)

ism = "anvar"
ism_json = json.dumps(ism)

sonlar = [12, 45, 23, 67]
sonlar_json = json.dumps(sonlar)

In [4]:
sonlar_json

'[12, 45, 23, 67]'

In [5]:
bemor = {
  "ism": "Alijon Valiyev",
  "yosh": 30,
  "oila": True,
  "farzandlar": ("Ahmad","Bonu"),
  "allergiya": None,
  "dorilar": [
    {"nomi": "Analgin", "miqdori": 0.5},
    {"nomi": "Panadol", "miqdori": 1.2}
  ]
}

bemor_json = json.dumps(bemor)

In [6]:
bemor_json

'{"ism": "Alijon Valiyev", "yosh": 30, "oila": true, "farzandlar": ["Ahmad", "Bonu"], "allergiya": null, "dorilar": [{"nomi": "Analgin", "miqdori": 0.5}, {"nomi": "Panadol", "miqdori": 1.2}]}'

In [7]:
print(bemor_json)

{"ism": "Alijon Valiyev", "yosh": 30, "oila": true, "farzandlar": ["Ahmad", "Bonu"], "allergiya": null, "dorilar": [{"nomi": "Analgin", "miqdori": 0.5}, {"nomi": "Panadol", "miqdori": 1.2}]}

In [8]:
bemor_json = json.dumps(bemor, indent=4)
print(bemor_json)

{
    "ism": "Alijon Valiyev",
    "yosh": 30,
    "oila": true,
    "farzandlar": [
        "Ahmad",
        "Bonu"
    ],
    "allergiya": null,
    "dorilar": [
        {
            "nomi": "Analgin",
            "miqdori": 0.5
        },
        {
            "nomi": "Panadol",
            "miqdori": 1.2
        }
    ]
}

In [11]:
import requests, json
r = requests.get('http://api.nobelprize.org/v1/laureate.json')
data = r.json()
# data['laureates']
pd.DataFrame(data['laureates'],)

,id,firstname,surname,born,died,bornCountry,bornCountryCode,bornCity,diedCountry,diedCountryCode,diedCity,gender,prizes
0,1,Wilhelm Conrad,RÃ¶ntgen,1845-03-27,1923-02-10,Prussia (now Germany),DE,Lennep (now Remscheid),Germany,DE,Munich,male,"[{'year': '1901', 'category': 'physics', 'shar..."
1,2,Hendrik A.,Lorentz,1853-07-18,1928-02-04,the Netherlands,NL,Arnhem,the Netherlands,NL,NaN,male,"[{'year': '1902', 'category': 'physics', 'shar..."
2,3,Pieter,Zeeman,1865-05-25,1943-10-09,the Netherlands,NL,Zonnemaire,the Netherlands,NL,Amsterdam,male,"[{'year': '1902', 'category': 'physics', 'shar..."
3,4,Henri,Becquerel,1852-12-15,1908-08-25,France,FR,Paris,France,FR,NaN,male,"[{'year': '1903', 'category': 'physics', 'shar..."
4,5,Pierre,Curie,1859-05-15,1906-04-19,France,FR,Paris,France,FR,Paris,male,"[{'year': '1903', 'category': 'physics', 'shar..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
976,1019,Memorial,NaN,1987-00-00,0000-00-00,NaN,NaN,NaN,NaN,NaN,NaN,org,"[{'year': '2022', 'category': 'peace', 'share'..."
977,1020,Center for Civil Liberties,NaN,2007-00-00,0000-00-00,NaN,NaN,NaN,NaN,NaN,NaN,org,"[{'year': '2022', 'category': 'peace', 'share'..."
978,1021,Ben,Bernanke,1953-12-13,0000-00-00,USA,US,"Augusta, GA",NaN,NaN,NaN,male,"[{'year': '2022', 'category': 'economics', 'sh..."
979,1022,Douglas,Diamond,1953-10-25,0000-00-00,USA,US,"Chicago, IL",NaN,NaN,NaN,male,"[{'year': '2022', 'category': 'economics', 'sh..."
980,1023,Philip,Dybvig,1955-05-22,0000-00-00,USA,US,"Gainesville, FL",NaN,NaN,NaN,male,"[{'year': '2022', 'category': 'economics', 'sh..."

In [12]:
r = requests.get("https://openlibrary.org/subjects/python.json?published_in=2015-2021")
pd.DataFrame(r.json()['works'])

,key,title,edition_count,cover_id,cover_edition_key,subject,ia_collection,lendinglibrary,printdisabled,lending_edition,lending_identifier,authors,first_publish_year,ia,public_scan,has_fulltext,availability
0,/works/OL17795703W,Python for bioinformatics,10,8078288.0,OL26385029M,"[Bioinformatics, Python (computer program lang...",[],False,False,,,"[{'key': '/authors/OL3871440A', 'name': 'Sebas...",2009,None,False,False,NaN
1,/works/OL6045694W,Python in a Nutshell,8,389166.0,OL7581267M,"[Python (Computer program language), Python (c...","[americanuniversity-ol, china, drakeuniversity...",False,True,OL24749091M,pythoninnutshell00mart,"[{'key': '/authors/OL1521655A', 'name': 'Alex ...",2002,pythoninnutshell00mart,False,True,"{'status': 'borrow_available', 'available_to_b..."
2,/works/OL23330617W,Making music with computers,7,NaN,None,"[Computer composition, Python (Computer progra...",[],False,False,,,"[{'key': '/authors/OL3853673A', 'name': 'Bill ...",2013,None,False,False,NaN
3,/works/OL21349037W,Introduction to Python for Science and Enginee...,6,NaN,None,"[Python (computer program language), Engineeri...",[],False,False,,,"[{'key': '/authors/OL4194836A', 'name': 'David...",2018,None,False,False,NaN
4,/works/OL21703042W,Tour of Data Science,6,NaN,None,"[Data mining, R (Computer program language), P...",[],False,False,,,"[{'key': '/authors/OL8302653A', 'name': 'Nailo...",2020,None,False,False,NaN
5,/works/OL19548251W,Python for Everyone,6,8514962.0,OL26838816M,"[Python (computer program language), Python (C...",[],False,False,,,"[{'key': '/authors/OL6972451A', 'name': 'Cay S...",2013,None,False,False,NaN
6,/works/OL14940051W,Natural Language Processing With Python,6,6296394.0,OL23978297M,"[Python (Computer program language), Natural l...","[librarygenesis, printdisabled]",False,True,,,"[{'key': '/authors/OL6770736A', 'name': 'Edwar...",2009,naturallanguagep00bird_504,False,True,"{'status': 'private', 'available_to_browse': F..."
7,/works/OL25217001W,Introduction to Python Programming,5,NaN,None,"[Python (computer program language), Python (C...",[],False,False,,,"[{'key': '/authors/OL9522029A', 'name': 'Gowri...",2018,None,False,False,NaN
8,/works/OL19932156W,Fluent Python,5,8743408.0,OL27112900M,"[Python (Computer program language), Computer ...","[binghamton-ol, cua-ol, inlibrary, internetarc...",False,True,OL27112900M,fluentpython0000rama,"[{'key': '/authors/OL7584543A', 'name': 'Lucia...",2015,fluentpython0000rama,False,True,"{'status': 'borrow_available', 'available_to_b..."
9,/works/OL25187574W,Introduction to Modeling and Simulation with M...,5,NaN,None,"[Matlab (computer program), Computer simulatio...",[],False,False,,,"[{'key': '/authors/OL953440A', 'name': 'Steven...",2017,None,False,False,NaN
10,/works/OL17308344W,Web Scraping with Python,5,7387255.0,OL25881956M,"[Python (Computer program language), Automatic...",[],False,False,,,"[{'key': '/authors/OL7495370A', 'name': 'Ryan ...",2015,None,False,False,NaN
11,/works/OL25347363W,Survival Analysis with Python,4,NaN,None,"[Structural analysis (Engineering), Python (Co...",[],False,False,,,"[{'key': '/authors/OL9588733A', 'name': 'Avish...",2021,None,False,False,NaN

In [14]:
r.json()

{'key': '/subjects/python',
 'name': 'python',
 'subject_type': 'subject',
 'work_count': 69,
 'works': [{'key': '/works/OL17795703W',
   'title': 'Python for bioinformatics',
   'edition_count': 10,
   'cover_id': 8078288,
   'cover_edition_key': 'OL26385029M',
   'subject': ['Bioinformatics',
    'Python (computer program language)',
    'Python (Computer program language)',
    'Computational Biology',
    'Bio-informatique',
    'Python (Langage de programmation)',
    'Programming languages (Electronic computers)',
    'Programming Languages',
    'Langages de programmation',
    'COMPUTERS',
    'Python',
    'NATURE',
    'Reference',
    'SCIENCE',
    'Life Sciences',
    'Biology',
    'General'],
   'ia_collection': [''],
   'lendinglibrary': False,
   'printdisabled': False,
   'lending_edition': '',
   'lending_identifier': '',
   'authors': [{'key': '/authors/OL3871440A', 'name': 'Sebastian Bassi'}],
   'first_publish_year': 2009,
   'ia': None,
   'public_scan': False,
   'has_fulltext': False},
  {'key': '/works/OL6045694W',
   'title': 'Python in a Nutshell',
   'edition_count': 8,
   'cover_id': 389166,
   'cover_edition_key': 'OL7581267M',
   'subject': ['Python (Computer program language)',
    'Python (computer program language)',
    'Python (programmeertaal)',
    'Scripting languages (Computer science)',
    'Python (Langage de programmation)',
    'COMPUTERS',
    'Programming Languages',
    'Python'],
   'ia_collection': ['americanuniversity-ol',
    'china',
    'drakeuniversity-ol',
    'inlibrary',
    'internetarchivebooks',
    'johnshopkins-ol',
    'librarygenesis',
    'printdisabled',
    'wilsoncollege-ol'],
   'lendinglibrary': False,
   'printdisabled': True,
   'lending_edition': 'OL24749091M',
   'lending_identifier': 'pythoninnutshell00mart',
   'authors': [{'key': '/authors/OL1521655A', 'name': 'Alex Martelli'},
    {'key': '/authors/OL2726934A', 'name': 'Anna Ravenscroft'},
    {'key': '/authors/OL2804309A', 'name': 'Steve Holden'}],
   'first_publish_year': 2002,
   'ia': 'pythoninnutshell00mart',
   'public_scan': False,
   'has_fulltext': True,
   'availability': {'status': 'borrow_available',
    'available_to_browse': True,
    'available_to_borrow': True,
    'available_to_waitlist': False,
    'is_printdisabled': True,
    'is_readable': False,
    'is_lendable': True,
    'is_previewable': True,
    'identifier': 'pythoninnutshell00mart',
    'isbn': '0596001886',
    'oclc': None,
    'openlibrary_work': 'OL15839297W',
    'openlibrary_edition': 'OL3703974M',
    'last_loan_date': '2020-08-17T04:02:58Z',
    'num_waitlist': '0',
    'last_waitlist_date': '2019-10-16T21:09:11Z',
    'is_restricted': True,
    'is_browseable': True,
    '__src__': 'core.models.lending.get_availability'}},
  {'key': '/works/OL23330617W',
   'title': 'Making music with computers',
   'edition_count': 7,
   'cover_id': None,
   'cover_edition_key': None,
   'subject': ['Computer composition',
    'Python (Computer program language)',
    'COMPUTERS / Programming Languages / General',
    'COMPUTERS / Programming / Algorithms',
    'MATHEMATICS / General',
    'Python (computer program language)',
    'Computer software',
    'Development',
    'Python (Langage de programmation)',
    'COMPUTERS',
    'Programming Languages',
    'Python'],
   'ia_collection': [''],
   'lendinglibrary': False,
   'printdisabled': False,
   'lending_edition': '',
   'lending_identifier': '',
   'authors': [{'key': '/authors/OL3853673A', 'name': 'Bill Manaris'}],
   'first_publish_year': 2013,
   'ia': None,
   'public_scan': False,
   'has_fulltext': False},
  {'key': '/works/OL21349037W',
   'title': 'Introduction to Python for Science and Engineering',
   'edition_count': 6,
   'cover_id': None,
   'cover_edition_key': None,
   'subject': ['Python (computer program language)',
    'Engineering, data processing',
    'Science, data processing',
    'Python (Computer program language)',
    'Computer programming',
    'Engineering',
    'Data processing',
    'Science',
    'COMPUTERS',
    'Programming Languages',
    'Python',
    'General',
    'MATHEMATICS',
    'SCIENCE',
    'Physics'],
   'ia_collection': [''],
   'lendinglibrary': False,
   'printdisabled': False,
   'lending_edition': '',
   'lending_identifier': '',
   'authors': [{'key': '/authors/OL4194836A', 'name': 'David J. Pine'}],
   'first_publish_year': 2018,
   'ia': None,
   'public_scan': False,
   'has_fulltext': False},
  {'key': '/works/OL21703042W',
   'title': 'Tour of Data Science',
   'edition_count': 6,
   'cover_id': None,
   'cover_edition_key': None,
   'subject': ['Data mining',
    'R (Computer program language)',
    'Python (Computer program language)',
    'Data Mining',
    'Exploration de donnÃ©es (Informatique)',
    'R (Langage de programmation)',
    'Python (Langage de programmation)',
    'COMPUTERS',
    'Programming Languages',
    'Python',
    'General',
    'Computer Graphics',
    'Game Programming & Design'],
   'ia_collection': [''],
   'lendinglibrary': False,
   'printdisabled': False,
   'lending_edition': '',
   'lending_identifier': '',
   'authors': [{'key': '/authors/OL8302653A', 'name': 'Nailong Zhang'}],
   'first_publish_year': 2020,
   'ia': None,
   'public_scan': False,
   'has_fulltext': False},
  {'key': '/works/OL19548251W',
   'title': 'Python for Everyone',
   'edition_count': 6,
   'cover_id': 8514962,
   'cover_edition_key': 'OL26838816M',
   'subject': ['Python (computer program language)',
    'Python (Computer program language)',
    'Python'],
   'ia_collection': [''],
   'lendinglibrary': False,
   'printdisabled': False,
   'lending_edition': '',
   'lending_identifier': '',
   'authors': [{'key': '/authors/OL6972451A', 'name': 'Cay S. Horstmann'},
    {'key': '/authors/OL7017980A', 'name': 'Rance D. Necaise'}],
   'first_publish_year': 2013,
   'ia': None,
   'public_scan': False,
   'has_fulltext': False},
  {'key': '/works/OL14940051W',
   'title': 'Natural Language Processing With Python',
   'edition_count': 6,
   'cover_id': 6296394,
   'cover_edition_key': 'OL23978297M',
   'subject': ['Python (Computer program language)',
    'Natural language processing (Computer science)',
    'Python <Programmiersprache>',
    'Sprachverarbeitung',
    'Python (computer program language)',
    'Natural language processing (computer science)',
    'Natural Language Processing',
    'Python (Langage de programmation)',
    'Traitement automatique des langues naturelles',
    'COMPUTERS',
    'Programming Languages',
    'Câ¯',
    'Java',
    'Pascal',
    'Python',
    'Natuurlijke-taalverwerking',
    'Python (programmeertaal)'],
   'ia_collection': ['librarygenesis', 'printdisabled'],
   'lendinglibrary': False,
   'printdisabled': True,
   'lending_edition': '',
   'lending_identifier': '',
   'authors': [{'key': '/authors/OL6770736A', 'name': 'Edward Loper'},
    {'key': '/authors/OL585313A', 'name': 'Steven Bird'},
    {'key': '/authors/OL3181508A', 'name': 'Ewan Klein'}],
   'first_publish_year': 2009,
   'ia': 'naturallanguagep00bird_504',
   'public_scan': False,
   'has_fulltext': True,
   'availability': {'status': 'private',
    'available_to_browse': False,
    'available_to_borrow': False,
    'available_to_waitlist': False,
    'is_printdisabled': True,
    'is_readable': False,
    'is_lendable': False,
    'is_previewable': False,
    'identifier': 'naturallanguagep00bird_504',
    'isbn': '9780596516499',
    'oclc': None,
    'openlibrary_work': 'OL14940051W',
    'openlibrary_edition': 'OL23978297M',
    'last_loan_date': None,
    'num_waitlist': None,
    'last_waitlist_date': None,
    'is_restricted': True,
    'is_browseable': False,
    '__src__': 'core.models.lending.get_availability'}},
  {'key': '/works/OL25217001W',
   'title': 'Introduction to Python Programming',
   'edition_count': 5,
   'cover_id': None,
   'cover_edition_key': None,
   'subject': ['Python (computer program language)',
    'Python (Computer program language)',
    'Python (Langage de programmation)',
    'COMPUTERS',
    'Programming Languages',
    'Python',
    'Programmierung'],
   'ia_collection': [''],
   'lendinglibrary': False,
   'printdisabled': False,
   'lending_edition': '',
   'lending_identifier': '',
   'authors': [{'key': '/authors/OL9522029A', 'name': 'Gowrishankar S'},
    {'key': '/authors/OL9522030A', 'name': 'Veena A'}],
   'first_publish_year': 2018,
   'ia': None,
   'public_scan': False,
   'has_fulltext': False},
  {'key': '/works/OL19932156W',
   'title': 'Fluent Python',
   'edition_count': 5,
   'cover_id': 8743408,
   'cover_edition_key': 'OL27112900M',
   'subject': ['Python (Computer program language)',
    'Computer programming',
    'Object-oriented programming languages',
    'Object-oriented programming (computer science)',
    'Python (computer program language)',
    'Python (Langage de programmation)',
    'Langages orientÃ©s objet (Informatique)',
    'COMPUTERS',
    'Programming Languages',
    'Python'],
   'ia_collection': ['binghamton-ol',
    'cua-ol',
    'inlibrary',
    'internetarchivebooks',
    'printdisabled',
    'universityofoklahoma-ol'],
   'lendinglibrary': False,
   'printdisabled': True,
   'lending_edition': 'OL27112900M',
   'lending_identifier': 'fluentpython0000rama',
   'authors': [{'key': '/authors/OL7584543A', 'name': 'Luciano Ramalho'}],
   'first_publish_year': 2015,
   'ia': 'fluentpython0000rama',
   'public_scan': False,
   'has_fulltext': True,
   'availability': {'status': 'borrow_available',
    'available_to_browse': True,
    'available_to_borrow': True,
    'available_to_waitlist': False,
    'is_printdisabled': True,
    'is_readable': False,
    'is_lendable': True,
    'is_previewable': True,
    'identifier': 'fluentpython0000rama',
    'isbn': '9781491946008',
    'oclc': None,
    'openlibrary_work': 'OL19932156W',
    'openlibrary_edition': 'OL27112900M',
    'last_loan_date': None,
    'num_waitlist': None,
    'last_waitlist_date': None,
    'is_restricted': True,
    'is_browseable': True,
    '__src__': 'core.models.lending.get_availability'}},
  {'key': '/works/OL25187574W',
   'title': 'Introduction to Modeling and Simulation with MATLABÂ® and Python',
   'edition_count': 5,
   'cover_id': None,
   'cover_edition_key': None,
   'subject': ['Matlab (computer program)',
    'Computer simulation',
    'Python (computer program language)',
    'Computer programming',
    'Engineering mathematics',
    'Python (Computer program language)',
    'Data processing',
    'Computer Simulation',
    'Simulation par ordinateur',
    'Python (Langage de programmation)',
    'Programmation (Informatique)',
    "MathÃ©matiques de l'ingÃ©nieur",
    'Informatique',
    'Simulation',
    'COMPUTERS',
    'Programming Languages',
    'Python',
    'Programming',
    'General',
    'Mathematical & Statistical Software',
    'MATLAB'],
   'ia_collection': [''],
   'lendinglibrary': False,
   'printdisabled': False,
   'lending_edition': '',
   'lending_identifier': '',
   'authors': [{'key': '/authors/OL953440A', 'name': 'Steven I. Gordon'},
    {'key': '/authors/OL9508251A', 'name': 'Brian Guilfoos'}],
   'first_publish_year': 2017,
   'ia': None,
   'public_scan': False,
   'has_fulltext': False},
  {'key': '/works/OL17308344W',
   'title': 'Web Scraping with Python',
   'edition_count': 5,
   'cover_id': 7387255,
   'cover_edition_key': 'OL25881956M',
   'subject': ['Python (Computer program language)',
    'Automatic data collection systems',
    'Data mining',
    'Python (computer program language)',
    'Electronic data processing, distributed processing',
    'Data Mining',
    'Python (Langage de programmation)',
    'Exploration de donnÃ©es (Informatique)',
    'Collecte automatique des donnÃ©es',
    'TECHNOLOGY & ENGINEERING',
    'Automation',
    'COMPUTERS',
    'Programming Languages',
    'Python'],
   'ia_collection': [''],
   'lendinglibrary': False,
   'printdisabled': False,
   'lending_edition': '',
   'lending_identifier': '',
   'authors': [{'key': '/authors/OL7495370A', 'name': 'Ryan Mitchell'}],
   'first_publish_year': 2015,
   'ia': None,
   'public_scan': False,
   'has_fulltext': False},
  {'key': '/works/OL25347363W',
   'title': 'Survival Analysis with Python',
   'edition_count': 4,
   'cover_id': None,
   'cover_edition_key': None,
   'subject': ['Structural analysis (Engineering)',
    'Python (Computer program language)',
    'COMPUTERS',
    'Programming Languages',
    'Python',
    'MATHEMATICS',
    'Probability & Statistics',
    'General'],
   'ia_collection': [''],
   'lendinglibrary': False,
   'printdisabled': False,
   'lending_edition': '',
   'lending_identifier': '',
   'authors': [{'key': '/authors/OL9588733A', 'name': 'Avishek Nag'}],
   'first_publish_year': 2021,
   'ia': None,
   'public_scan': False,
   'has_fulltext': False}]}